### PR TITLE
fix: Enable IMDsv2

### PR DESCRIPTION
**Pull request by wandb-zacharyblasczyk**
https://wandb.atlassian.net/browse/WB-12607

### CODE REVIEW

**Review by vanpelt — APPROVED** [review]
Looks great.  Could this cause issues or downtime for self-hosted customers on older versions of our module?

**Comment by wandb-zacharyblasczyk** [comment]
@vanpelt, anyone upgrading past [v1.10.0](https://github.com/wandb/terraform-aws-wandb/releases/tag/v1.10.0) will experience about a 3-5 min outage because of the need for new node groups being added for launch templates and the way iam polices are updated.

Anyone past that version will only experience the pod recycling after the new nodes are added to the cluster.

**Comment by wandb-zacharyblasczyk** [comment]
Rebased**

**Comment by jsbroks** [comment]
This PR is included in version 1.10.2 :tada:

**Pull request merged**
