### PR TITLE
feat: New kubernetes_instance_types variable

### PR DESCRIPTION
**Pull request by wandb-zacharyblasczyk**
This PR allows for instance types to be configured via `kubernetes_instance_types`.

### CODE REVIEW

**Review by vanpelt — APPROVED** [review]

**Review by vanpelt — APPROVED** [review]
🔥

**Review by venky-wandb — APPROVED** [review]
🚀

**Comment by venky-wandb** [comment]
Make sure to resolve conflicts before merging! 👍

**Comment by jsbroks** [comment]
This PR is included in version 1.8.0 :tada:

**Pull request merged**
