### PR TITLE
fix: Naming Conventions

### PR DESCRIPTION
**Pull request by zacharyblasczyk**
* Changed `db_kms_key_arn` to `database_kms_key_arn` to match our conventions. 
* Ran a `terraform-docs markdown` to update the readme.

### CODE REVIEW

**Comment by jsbroks** [comment]
Won't this be a break change?

**Comment by jsbroks** [comment]
Do we want to release a breaking change just to rename stuff?

**Review by danielpanzella — APPROVED** [review]

**Comment by jsbroks** [comment]
you'll have to make it `fix!:` so it releases a new version

**Review by jsbroks — CHANGES_REQUESTED** [review]
pending on breaken change

**Comment by zacharyblasczyk** [comment]
> Won't this be a break change?

I really don't think anyone has used this yet. If you want me to make it a breaking, I can, but this is just a simple mistake caught early before adoption IMO.

**Pull request merged**
